ALIAS.COLUMN
ALIAS.COLUMN nIdElement
IF(ALIAS.COLUMN, DATE_FORMAT(ALIAS.COLUMN, \'%d/%m/%Y\'), \'\') AS NAME
IF(ALIAS.COLUMN, DATE_FORMAT(ALIAS.COLUMN, \'%d/%m/%Y à %H\h%i\'), \'\') AS NAME
IF(ALIAS.COLUMN, TIME_FORMAT(ALIAS.COLUMN, \'%H\h%i\'), \'\') AS NAME
REPLACE(ALIAS.COLUMN, \'.\', \',\') AS NAME
(CASE WHEN ALIAS.COLUMN = 1 THEN \'oui\' ELSE \'non\' END) AS NAME
IF(ALIAS.COLUMN,' . $this->sGetClauseCase('ALIAS.COLUMN', $this->szGetParametreModule('mODULE', 'aListe-MODEL-COLUMN')) . ', \'\') NAME
IFNULL(ALIAS.valeur, \'\') FIELD
IFNULL(FKALIAS.LABEL, \'\' ) CONCATALIAS
(
    SELECT LABEL
    FROM FKTABLE
    WHERE PK = ALIAS.PK
) FIELD