ALIAS.COLUMN
ALIAS.COLUMN nIdElement
CASE WHEN ALIAS.COLUMN != \'\' THEN TO_CHAR(ALIAS.COLUMN, \'DD/MM/YYYY\') ELSE \'\' END AS NAME
CASE WHEN ALIAS.COLUMN != \'\' THEN TO_CHAR(ALIAS.COLUMN, \'DD/MM/YYYY "à" HH24"h"MM\') ELSE \'\' END AS NAME
CASE WHEN ALIAS.COLUMN != \'\' THEN TO_CHAR(ALIAS.COLUMN, \'HH24"h" MM\') ELSE \'\'  END AS NAME
REPLACE(ALIAS.COLUMN, \'.\', \',\') AS NAME
(CASE WHEN ALIAS.COLUMN = 1 THEN \'oui\' ELSE \'non\' END) AS NAME
$this->sGetClauseCase("NVL('ALIAS.COLUMN', \'\')", $this->szGetParametreModule('mODULE', 'aListe-MODEL-COLUMN')) . ' NAME
NVL(ALIAS.valeur, \'\') FIELD
NVL(FKALIAS.LABEL, \'\' ) CONCATALIAS
(
    SELECT LABEL
    FROM FKTABLE
    WHERE PK = ALIAS.PK
) FIELD