aLibellesTypesParametres:
    cursus_grille_annee: "Année"
    cursus_grille_discipline_categorie: "Catégorie de discipline dans les cursus"
    cc_concours_categorie: "catégorie des concours"
    concours: "Concours"
    csp: "CSP"
    cursus_cycle: "Cycle"
    diplome_date_commission: "Date de comission diplôme"
    diplome_libelle: "Diplôme/libellé"
    diplome_specialite: "Diplôme/spécialité"
    diplome_champ: "Diplôme/champ"
    formation_pro_dispositif: "Disposition pro formation"
    insc_adm_doc_a_signer: "Document à signer pour l'inscription administrative"
    insc_adm_doc: "Document d'inscription administrative"
    bourse_echelon: "Echelon de bourse"
    insc_adm_etat: "Etat de l'inscription administrative"
    cc_concours_candidature_etat: "Etat des candidatures des concours"
    cc_concours_candidature_etat: "Etat pédagogique des candidatures des concours"
    cursus_famille_diplome: "Famille de diplômes"
    discipline_famille: "Famille de discipline"
    formation_financeur: "Financeur de formation"
    cc_concours_groupe_paiement: "Groupe de paiement"
    cc_concours_inscription: "Inscription aux concours"
    cursus_langue: 'Langue'
    libelle_ue: 'Libellés de UE'
    cursus_grille_discipline_mode_inscription: "Mode d'inscription dans les cursus"
    paiement_etudiant_moyen_paiement: "Moyen de paiement"
    paiement_multiple: "Paiements multiples"
    etudiant_cursus_grille_discipline_precision_notation: "Précision de notation"
    cursus_grille_discipline_regle_validation: 'Règles de validation des disciplines de cursus'
    etudiant_cursus_grille_controle_resultat: "Résultat des contrôles"
    classe_enseignant_role: "Rôle des enseignants dans les classes"
    planning_enseignant_role: "Rôle des enseignants dans les plannings"
    scolarite: "Scolarité"
    etudiant_bac_section: "Section du bac"
    etudiant_cursus_statut: "Statut des cursus étudiants"
    planning_etudiant_statut: "Statut du planning étudiant"
    etudiant_situation_annee_precedente: "Situation de l'année précédente"
    etudiant_cursus_tag: "Tag des cursus étudiant"
    texte_pied_mail: "Texte de pied de mail"
    epreuve_type: "Type d'épreuve"
    etudiant_type: "Type d'étudiant"
    etudiant_cursus_info_complementaire_type: "Type d'information complémentaire"
    bourse_type: "Type de bourse"
    calendrier_type: "Type de calendrier"
    document_type_code: "Type code document"
    commentaire_type: "Type de commentaire"
    cursus_grille_discipline_controle_type: "Types de contrôles"
    coordonnee_type: "Type de coordonnées"
    etudiant_dernier_diplome_type: "Type de dernier diplôme"
    discipline_type: "Type de discipline"
    document_type: "Type de document"
    formation_groupe_type: "Type de formation pour les groupes"
    absence_justificatif_type: "Type de justificatif d'absence"
    document_modele_type: "Type de modèle de document"
    etudiant_cursus_grille_discipline_validation: "Validation des disciplines"
    salle_site: "Sites des salles"
    salle_type: "Type de salles"
    ct_mode_engagement: "Mode engagement des contrats"
    ct_type_cours: "Types de cours des contrats"
    ct_type_transport: "Types de transport contrat"
    ct_etat_contrat_element: "Etat élément de contrat"
    ct_type_contrat: "Types de contrats"
    ct_etat_contrat: "Etats de contrat"
    etat_cours: "Etats des cours"
    planning_categorie: "Catégorie des évènements"
