btn_dynamisation_recherche_TABLE:
    action:
        module: mODULE
        route: json_dynamisation_recherche_TABLE
        type: load_data
    callback:
        module: cONTROLLER
        fonction: vDynamisationFormulaireRechercheMODEL
        alerte: non

btn_ouverture_consultation_TABLE:
    action:
        module: mODULE
        route: json_dynamisation_consultation_TABLE
        type: load_data
    callback:
        module: cONTROLLER
        fonction: vDynamisationConsultationMODELJSON
        alerte: non

btn_ouverture_edition_TABLE:
    action:
        module: mODULE
        route: json_dynamisation_edition_TABLE
        type: load_data
    callback:
        module: cONTROLLER
        fonction: vDynamisationEditionMODELJSON
        alerte: non

btn_enregistre_edition_TABLE:
    action:
        module: mODULE
        route: json_enregitre_edition_TABLE
        type: save_data
        save_formulaire: formulaire_edition_TABLE
    callback:
        module: cONTROLLER
        fonction: vFermeEditionRefreshListe
        alerte: non

btn_suppression_TABLE:
    action:
        module: mODULE
        route: json_suppression_TABLE
        type: save_data
    callback:
        module: cONTROLLER
        fonction: vRefreshListe
        alerte: non
