btn_ouverture_consultation_mODEL:
    action:
        module: mODULE
        route: json_dynamisation_consultation_mODEL
        type: load_data
    callback:
        module: cONTROLLER
        fonction: vDynamisationConsultationMODELJSON
        alerte: non
