btn_ouverture_edition_mODEL:
    action:
        module: mODULE
        route: json_dynamisation_edition_mODEL
        type: load_data
    callback:
        module: cONTROLLER
        fonction: vDynamisationEditionMODELJSON
        alerte: non

btn_enregistre_edition_mODEL:
    action:
        module: mODULE
        route: json_enregistre_edition_mODEL
        type: save_data
        save_formulaire: formulaire_edition_mODEL
    callback:
        module: cONTROLLER
        fonction: vFermeEditionEtRefreshListe
        alerte: non
