btn_dynamisation_recherche_TABLE:
    action:
        module: mODULE
        route: json_dynamisation_recherche_TABLE
        type: load_data
    callback:
        module: cONTROLLER
        fonction: vDynamisationFormulaireRecherche
        alerte: non
