btn_dynamisation_recherche_mODEL:
    action:
        module: mODULE
        route: json_dynamisation_recherche_mODEL
        type: load_data
    callback:
        module: cONTROLLER
        fonction: vDynamisationFormulaireRecherche
        alerte: non
