btn_dynamisation_recherche_mODEL:
    action:
        module: mODULE
        route: json_dynamisation_recherche_mODEL
        type: load_data
    callback:
        module: cONTROLLER
        fonction: vDynamisationFormulaireRechercheMODEL
        alerte: non

btn_ouverture_consultation_mODEL:
    action:
        module: mODULE
        route: json_dynamisation_consultation_mODEL
        type: load_data
    callback:
        module: cONTROLLER
        fonction: vDynamisationConsultationMODELJSON
        alerte: non

btn_ouverture_edition_mODEL:
    action:
        module: mODULE
        route: json_dynamisation_edition_mODEL
        type: load_data
    callback:
        module: cONTROLLER
        fonction: vDynamisationEditionMODELJSON
        alerte: non

btn_enregistre_edition_mODEL:
    action:
        module: mODULE
        route: json_enregitre_edition_mODEL
        type: save_data
        save_formulaire: formulaire_edition_mODEL
    callback:
        module: cONTROLLER
        fonction: vFermeEditionRefreshListe
        alerte: non

btn_suppression_mODEL:
    action:
        module: mODULE
        route: json_suppression_mODEL
        type: save_data
    callback:
        module: cONTROLLER
        fonction: vRefreshListe
        alerte: non

btn_export_mODEL:
    action:
        module:             mODULE
        route:              xlsx_export_mODEL
        type:               download_csv
        save_formulaire:    formulaire_recherche_mODEL