btn_suppression_mODEL:
    action:
        module: mODULE
        route: json_suppression_mODEL
        type: save_data
    callback:
        module: cONTROLLER
        fonction: vFermeConsultationEtRefreshListe
        alerte: non
