btn_ouverture_consultation_TABLE:
    action:
        module: mODULE
        route: json_dynamisation_consultation_TABLE
        type: load_data
    callback:
        module: cONTROLLER
        fonction: vDynamisationConsultationMODELJSON
        alerte: non
