aNamespace:
    HTML:
        CONTROLLERAdminHTML: APP\Modules\MODULE\Controllers\CONTROLLERAdminHTML
    data:
        MODEL: APP\Modules\MODULE\Models\MODEL
        CONTROLLERAdminAction: APP\Modules\MODULE\Controllers\CONTROLLERAdminAction

aVues:
    cONTROLLER:
        admin:
            simples:
                accueil_mODEL:
                    ressources:
                        CSS:
                            modules:
                                - mODULE/templates/defaut/themes/defaut/css/mURL.css
                            lib_externe_dist:
                                - package-plugins-light/JS/Select2/css/select2.min.css
                        JS:
                            modules:EXPORTJS
                                - mODULE/JS/CONTROLLERAdmin.js
                                - mODULE/JS/CONTROLLER.js
                            lib_externe_dist:
                                - package-plugins-light/JS/jQuery-Mask/jquery.mask.js
                                - package-plugins-light/JS/Select2/select2.min.js
                consultation_mODEL:
                    ressources:
                        CSS: []
                        JS: []

            formulaires:
                edition_mODEL:
                    classe: MODEL
                    ressources:
                        CSS: []
                        JS:
                            modules:
                                - mODULE/JS/CONTROLLERAdmin.js
                                - mODULE/JS/CONTROLLER.js
            specifiques: []
ENUMS:EXPORT