aNamespace:
    HTML:
        MODULEAdminHTML: APP\Modules\MODULE\Controllers\MODULEAdminHTML
    data:
        MODEL: APP\Modules\MODULE\Models\MODEL
        MODULEAdminAction: APP\Modules\MODULE\Controllers\MODULEAdminAction

aVues:
    TABLE:
        admin:
            simples:
                accueil_TABLE:
                    ressources:
                        CSS:
                            modules:
                                - mODULE/templates/defaut/themes/defaut/css/TABLE.css
                            lib_externe_dist:
                                - package-plugins-light/JS/Select2/css/select2.min.css
                        JS:
                            modules:
                                - mODULE/JS/MODELAdmin.js
                                - mODULE/JS/MODEL.js
                            lib_externe_dist:
                                package-plugins-light/JS/jQuery-Mask/jquery.mask.js
                                package-plugins-light/JS/Select2/select2.min.js
                consultation_TABLE:
                    ressources:
                        CSS: []
                        JS: []

            formulaires:
                edition_TABLE:
                    classe: MODEL
                    ressources:
                        CSS: []
                        JS:
                            modules:
                                - mODULE/JS/MODELAdmin.js
                                - mODULE/JS/MODEL.js
            specifiques: []
ENUMS