json_suppression_mODEL:
    reecriture: admin/mODULE/mURL/(\d+)/suppression.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: suppression
        variables:
            - nIdElement
