html_consultation_mODEL:
    reecriture: admin/mODULE/mURL/consultation.html
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        mode: consultation_mODEL

json_dynamisation_consultation_mODEL:
    reecriture: admin/mODULE/mURL/(\d+)/dynamisation-consultation.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: dynamisation_consultation
        variables:
            - nIdElement
