html_accueil_TABLE:
    reecriture: admin/mODULE/mODEL/accueil.html
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        mode: accueil_TABLE

json_recherche_TABLE:
    reecriture: admin/mODULE/mODEL/recherche.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: recherche

html_consultation_TABLE:
    reecriture: admin/mODULE/mODEL/consultation.html
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        mode: consultation_TABLE

json_dynamisation_consultation_TABLE:
    reecriture: admin/mODULE/mODEL/\d+/dynamisation-consultation.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: dynamisation_consultation
        variables:
            - nIdElement

html_edition_TABLE:
    reecriture: admin/mODULE/mODEL/edition.html
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        mode: edition_TABLE

json_dynamisation_edition_TABLE:
    reecriture: admin/mODULE/mODEL/\d+/edition.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: edition
        variables:
            - nIdElement

json_enregistre_edition_TABLE:
    reecriture: admin/mODULE/mODEL/\d+/enregistre-edition.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: enregistrement
        variables:
            - nIdElement

json_suppression_TABLE:
    reecriture: admin/mODULE/mODEL/\d+/suppression.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: suppression
        variables:
            - nIdElement