html_accueil_mODEL:
    reecriture: admin/mODULE/mURL/accueil.html
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        mode: accueil_mODEL

json_recherche_mODEL:
    reecriture: admin/mODULE/mURL/recherche.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: recherche
