html_edition_mODEL:
    reecriture: admin/mODULE/mURL/edition.html
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        mode: edition_mODEL

json_dynamisation_edition_mODEL:
    reecriture: admin/mODULE/mURL/(\d+)/edition.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: dynamisation_edition
        variables:
            - nIdElement

json_enregistre_edition_mODEL:
    reecriture: admin/mODULE/mURL/(\d+)/enregistre-edition.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: enregistre_edition
        variables:
            - nIdElement
