html_accueil_mODEL:
    reecriture: admin/mODULE/mURL/accueil.html
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        mode: accueil_mODEL

json_recherche_mODEL:
    reecriture: admin/mODULE/mURL/recherche.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: recherche

html_consultation_mODEL:
    reecriture: admin/mODULE/mURL/consultation.html
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        mode: consultation_mODEL

json_dynamisation_consultation_mODEL:
    reecriture: admin/mODULE/mURL/\d+/dynamisation-consultation.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: dynamisation_consultation
        variables:
            - nIdElement

html_edition_mODEL:
    reecriture: admin/mODULE/mURL/edition.html
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        mode: edition_mODEL

json_dynamisation_edition_mODEL:
    reecriture: admin/mODULE/mURL/\d+/edition.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: edition
        variables:
            - nIdElement

json_enregistre_edition_mODEL:
    reecriture: admin/mODULE/mURL/\d+/enregistre-edition.json
    route:
        zone: adminf
        module: mODULE
        controller: cONTROLLER
        action: enregistrement
        variables:
            - nIdElement

json_suppression_mODEL:
    reecriture: admin/mODULE/mURL/\d+/suppression.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: suppression
        variables:
            - nIdElement

xlsx_export_mODEL:
    reecriture: admin/mODULE/mURL/export.xlsx
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: export_mODEL