html_edition_TABLE:
    reecriture: admin/mODULE/mODEL/edition.html
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        mode: edition_TABLE

json_dynamisation_edition_TABLE:
    reecriture: admin/mODULE/mODEL/(\d+)/edition.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: dynamisation_edition
        variables:
            - nIdElement

json_enregistre_edition_TABLE:
    reecriture: admin/mODULE/mODEL/(\d+)/enregistre-edition.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: enregistre_edition
        variables:
            - nIdElement
