html_accueil_TABLE:
    reecriture: admin/mODULE/mODEL/accueil.html
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        mode: accueil_TABLE

json_recherche_TABLE:
    reecriture: admin/mODULE/mODEL/recherche.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: recherche
