json_dynamisation_recherche_TABLE:
    reecriture:     admin/mODULE/TABLE/dynamisation-recherche.json
    route:
        zone:       admin
        module:     mODULE
        controller: TABLE
        action:     dynamisation_recherche
