json_suppression_TABLE:
    reecriture: admin/mODULE/mODEL/(\d+)/suppression.json
    route:
        zone: admin
        module: mODULE
        controller: cONTROLLER
        action: suppression
        variables:
            - nIdElement
