btn_ouverture_consultation_%2$s:
    action:
        module: %1$s
        route: json_dynamisation_consultation_%2$s
        type: load_data
    callback:
        module: %1$s
        fonction: vDynamisationConsultation%3$sJSON
        alerte: non
