btn_(ouverture_consultation)_(model):
    action:
        module: (module)
        route: json_(dynamisation_consultation)_(model)
        type: load_data
    callback:
        module: (model)
        fonction: vDynamisationConsultation(Model)JSON
        alerte: non

btn_(ouverture_edition)_(model):
    action:
        module: (module)
        route: json_(dynamisation_edition)_(model)
        type: load_data
    callback:
        module: (model)
        fonction: vDynamisationEdition(Model)JSON
        alerte: non

btn_(enregistrement)_(model):
    action:
        module: (module)
        route: json_(enregitrement)_(model)
        type: save_data
        save_formulaire: formulaire_edition_(model)
    callback:
        module: (module)
        fonction: vFermeEditionRefreshListe
        alerte: non

btn_(suppression)_(model):
    action:
        module: (module)
        route: json_(suppression)_(model)
        type: save_data