btn_ouverture_edition_TABLE:
    action:
        module: mODULE
        route: json_dynamisation_edition_TABLE
        type: load_data
    callback:
        module: mODULE
        fonction: vDynamisationEditionMODELJSON
        alerte: non

btn_enregistre_edition_TABLE:
    action:
        module: mODULE
        route: json_enregistre_edition_TABLE
        type: save_data
        save_formulaire: formulaire_edition_TABLE
    callback:
        module: mODULE
        fonction: vFermeEditionEtRefreshListe
        alerte: non
