btn_suppression_%2$s:
    action:
        module: %1$s
        route: json_suppression_%2$s
        type: save_data
    callback:
        module: %1$s
        fonction: vRefreshListe
        alerte: non
