btn_suppression_TABLE:
    action:
        module: mODULE
        route: json_suppression_TABLE
        type: save_data
    callback:
        module: mODULE
        fonction: vRefreshListe
        alerte: non
