calque_consultation_TABLE:
    route: html_consultation_TABLE
    priorite: 1
    ordre: 1
    callback: ''
    module: mODULE
    zones_affichage:
        - admin
    auto_reset: oui
    module_callback: ''
    largeur: large
    cache:
        html: oui
        base: oui
