html_consultation_TABLE:
    reecriture: admin/mODULE/TABLE/consultation.html
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        mode: consultation_TABLE

json_dynamisation_consultation_TABLE:
    reecriture: admin/mODULE/TABLE/(\d+)/dynamisation-consultation.json
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        action: dynamisation_consultation
        variables:
            - nIdElement
