html_accueil_TABLE:
    reecriture: admin/mODULE/TABLE/accueil.html
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        mode: accueil_TABLE

json_recherche_TABLE:
    reecriture: admin/mODULE/TABLE/recherche.json
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        action: recherche

html_consultation_TABLE:
    reecriture: admin/mODULE/TABLE/consultation.html
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        mode: consultation_TABLE

json_dynamisation_consultation_TABLE:
    reecriture: admin/mODULE/TABLE/\d+/dynamisation-consultation.json
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        action: dynamisation_consultation
        variables:
            - nIdElement

html_edition_TABLE:
    reecriture: admin/mODULE/TABLE/edition.html
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        mode: edition_TABLE

json_dynamisation_edition_TABLE:
    reecriture: admin/mODULE/TABLE/\d+/edition.json
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        action: edition
        variables:
            - nIdElement

json_enregistre_edition_TABLE:
    reecriture: admin/mODULE/TABLE/\d+/enregistre-edition.json
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        action: enregistrement
        variables:
            - nIdElement

json_suppression_TABLE:
    reecriture: admin/mODULE/TABLE/\d+/suppression.json
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        action: suppression
        variables:
            - nIdElement