html_edition_TABLE:
    reecriture: admin/mODULE/TABLE/edition.html
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        mode: edition_TABLE

json_dynamisation_edition_TABLE:
    reecriture: admin/mODULE/TABLE/(\d+)/edition.json
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        action: dynamisation_edition
        variables:
            - nIdElement

json_enregistre_edition_TABLE:
    reecriture: admin/mODULE/TABLE/(\d+)/enregistre-edition.json
    route:
        zone: admin
        module: mODULE
        controller: TABLE
        action: enregistre_edition
        variables:
            - nIdElement
