html_consultation_%2$s:
    reecriture: admin/%1$s/%2$s/consultation.html
    route:
        zone: admin
        module: %1$s
        controller: %2$s
        mode: consultation_%2$s

json_dynamisation_consultation_%2$s:
    reecriture: admin/%1$s/%2$s/(\d+)/dynamisation-consultation.json
    route:
        zone: admin
        module: %1$s
        controller: %2$s
        action: dynamisation_consultation
        variables:
            - nIdElement
