son_suppression_%2$s:
    reecriture: admin/%1$s/%2$s/(\d+)/suppression.json
    route:
        zone: admin
        module: %1$s
        controller: %2$s
        action: suppression
        variables:
            - nIdElement