html_accueil_%2$s:
    reecriture: admin/%1$s/%2$s/accueil.html
    route:
        zone: admin
        module: %1$s
        controller: %2$s
        mode: accueil_%2$s

json_recherche_%2$s:
    reecriture: admin/%1$s/%2$s/recherche.json
    route:
        zone: admin
        module: %1$s
        controller: %2$s
        action: recherche

html_consultation_%2$s:
    reecriture: admin/%1$s/%2$s/consultation.html
    route:
        zone: admin
        module: %1$s
        controller: %2$s
        mode: consultation_%2$s

json_dynamisation_consultation_%2$s:
    reecriture: admin/%1$s/%2$s/\d+/dynamisation-consultation.json
    route:
        zone: admin
        module: %1$s
        controller: %2$s
        action: dynamisation_consultation
        variables:
            - nIdElement

html_edition_%2$s:
    reecriture: admin/%1$s/%2$s/edition.html
    route:
        zone: admin
        module: %1$s
        controller: %2$s
        mode: edition_%2$s

json_dynamisation_edition_%2$s:
    reecriture: admin/%1$s/%2$s/\d+/edition.json
    route:
        zone: admin
        module: %1$s
        controller: %2$s
        action: edition
        variables:
            - nIdElement

json_enregistre_edition_%2$s:
    reecriture: admin/%1$s/%2$s/\d+/enregistre-edition.json
    route:
        zone: admin
        module: %1$s
        controller: %2$s
        action: enregistrement
        variables:
            - nIdElement

json_suppression_%2$s:
    reecriture: admin/%1$s/%2$s/\d+/suppression.json
    route:
        zone: admin
        module: %1$s
        controller: %2$s
        action: suppression
        variables:
            - nIdElement